---
groups:
  staging:
    description: Staging environments
    environments:
    - staging
    - staging-s2
    - staging-s3
    - staging-s101
    - staging-s201
  prod:
    description: All production environments
    environments:
    - prod
    - prod-s2
    - prod-s3
    - prod-s4
    - prod-s5
    - prod-s6
    - prod-s7
    - prod-s8
    - prod-s9
    - prod-s101
    - prod-s201
  us-prod:
    description: All US production environments
    environments:
    - prod
    - prod-s2
    - prod-s3
    - prod-s4
    - prod-s5
    - prod-s6
    - prod-s7
    - prod-s8
    - prod-s9
  eu-prod:
    description: All EU production environments
    environments:
    - prod-s101
  apse-prod:
    description: All AP Southeast production environments
    environments:
    - prod-s201
  us-staging:
    description: All US staging environments
    environments:
    - staging
    - staging-s2
    - staging-s3
  eu-staging:
    description: All EU staging environments
    environments:
    - staging-s101
  apse-staging:
    description: All AP Southeast staging environments
    environments:
    - staging-s201