AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

# Increase limits for CLI tool complexity
Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

# Allow OpenStruct for CLI options
Style/OpenStructUse:
  Exclude:
    - 'lib/lsql/command_line_parser.rb'

# Allow predicate methods that don't end with ?
Naming/PredicateMethod:
  Enabled: false

# Allow get_ prefixed methods
Naming/AccessorMethodName:
  Enabled: false

# Development dependencies are fine in gemspec for now
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow duplicate branches in conditional logic
Lint/DuplicateBranch:
  Enabled: false

# Disable some naming conventions that are less important
Naming/PredicatePrefix:
  Enabled: false

# Allow some complexity in output aggregation logic
Lint/EmptyConditionalBody:
  Enabled: false

Style/EmptyElse:
  Enabled: false
